remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "air"  # hoặc: air, aqua, contrast, dirt, mint, neon, plum, sunset
# air	Sáng, thoáng, nhiều khoảng trắng — hợp portfolio dev
# dark	Nền tối, chữ sáng — hợp blog technical
# mint	Sáng, điểm nhấn xanh mint, hiện đại
# contrast	Tương phản cao, rõ ràng, dễ đọc

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

title: "Thao Nguyen"
url: "https://thaonbt.github.io"

breadcrumbs: true

author:
  name: "Thao Nguyen"
  bio: "Full-stack dev | Fintech & Crypto enthusiast"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/thaonbt"

logo: /assets/images/avatar_Thao.

collections:
  projects:
    output: true
    permalink: /:collection/:path/

include:
  - _pages